baseURL = 'https://etheriamagazine.com/'
title = 'Hugo Etheria Theme'
languageCode = 'es-ES'
defaultContentLanguage = "es"
summaryLength = 20

[permalinks]

    [permalinks.taxonomy]
        categories = "/categorias"

    [permalinks.term]
        categories = "/categorias/:slug"

[minify]
    minifyOutput = true

[module]
    [[module.imports]]
        path = 'github.com/etheriamagazine/hugo-mod-jslibs/preact-bundle'

    [[module.imports]]
        path = 'github.com/etheriamagazine/hugo-mod-jslibs/alpinejs/v3'


    # Cloudflare Pages functions 
    [[module.mounts]]
        source = 'functions'
        target = 'functions'

    # Standard Hugo mounts used
    [[module.mounts]]
        source = 'archetypes'
        target = 'archetypes'

    [[module.mounts]]
        source = 'assets'
        target = 'assets'

    [[module.mounts]]
        source = 'layouts'
        target = 'layouts'

    [[module.mounts]]
        source = 'static'
        target = 'static'

    # [[module.mounts]]
    #     source = 'content'
    #     target = 'content'

    # [[module.mounts]]
    #     source = 'data'
    #     target = 'data'

    # [[module.mounts]]
    #     source = 'i18n'
    #     target = 'i18n'
