baseURL = 'https://example.org/'
title = 'Hugo Etheria theme'
languageCode = 'es-ES'
defaultContentLanguage =  "es"

# [module]
#   [[module.mounts]]
#     source = "test_content"
#     target = "content"